### ISSUE TITLE
Unable to inject reducer

### ISSUE THREAD

**Issue by shahzad185** [lundegaard/redux-tools#150]
Hi There
I am working on a project using Liferay 7.2 and widgets for react application.
While I am trying to inject reducer from root component getting following error:

redux-tools-injectors-react.js?9087:140 Uncaught TypeError: getInject is not a function
    at useInjectables (redux-tools-injectors-react.js?9087:140)
    at WithReducers(Connect(Root)) (redux-tools-injectors-react.js?9087:217)
    at renderWithHooks (react-dom.development.js?4b4a:14826)
    at mountIndeterminateComponent (react-dom.development.js?4b4a:17506)
    at beginWork (react-dom.development.js?4b4a:18630)
    at HTMLUnknownElement.callCallback (react-dom.development.js?4b4a:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?4b4a:238)
    at invokeGuardedCallback (react-dom.development.js?4b4a:293)
    at beginWork$1 (react-dom.development.js?4b4a:23235)
    at performUnitOfWork (react-dom.development.js?4b4a:22186)

The above error occurred in the <WithReducers(Connect(Root))> component:
    in WithReducers(Connect(Root)) (created by UniversalComponent)
    in UniversalComponent (created by Widget)
    in Widget (created by WithErrorBoundary(Widget))
    in WithErrorBoundary(Widget) (created by Union)
    in Union
    in Provider (created by Provider)
    in Provider
    in Root (created by HotExportedRoot)
    in AppContainer (created by HotExportedRoot)
    in HotExportedRoot

//Root file is :
import React, { createContext, useMemo } from "react";
import { useStore,connect,ReactReduxContext } from "react-redux";
import { ConnectedRouter } from "connected-react-router";

import Journey from "../journey";
import definition from "../test.journey.json";
import { history} from "../utils" ;
import adamReducer /*,{adamEpic,selectAdamFields,fetchAdam}*/ from "../ducks/adam";
import { compose } from "ramda";
import { withReducers} from "@redux-tools/reducers-react";

const Root = () => {
  
  
  //Acutal code that needs to be rendered and connected to store
  
  let store =useStore();

  return (    
    <ConnectedRouter {...{ history }} context={ReactReduxContext} >    
        <Journey definition={definition} store={store} context={ReactReduxContext} />      
    </ConnectedRouter>       
      
  ); 
}

//export default connect()(Root);
 export default compose(  
  withReducers(
    {
      adam: adamReducer,
      
    },
    { isGlobal: true }
  ),
  connect())(Root);

// adamReducer is:
const initialState = {
    router: connectRouter(history),
    data: [],    
  }; 
  
  // reducers
  export default makeReducer(
    [
      [
        ActionTypes.FETCH,
        state => ({
          ...state    
        })
      ],    
     
    ],
    initialState
  );
  
Will appreciate any support and feel free to contact me if you need additional information.
Thanks in advance.

**Comment by wafflepie** [comment]
Hey there, judging by the error message containing `getInject`, which is from a pretty old version of Redux Tools, this might be caused by a dependency version mismatch. All of your Redux Tools dependencies need to have the same major version.

I recommend using the newest version of `@redux-tools/react`, which reexports all the necessary packages you need (except for epics, if you do use them). If you don't feel like refactoring your imports, make sure that all of the Redux Tools dependencies have the same version (you can check this in your lockfile).

Let me know if this solves your issue.

**Comment by shahzad185** [comment]
I could see there was a conflict for "@redux-tools/reducers-react as in other widgets where it is working it was "@redux-tools/reducers-react": "^0.5.0", while in my widget it was "@redux-tools/reducers-react": "^0.6.0",
(in other widgets where reducer injection is working the modules are as follows:
"@redux-tools/actions": "^0.6.0",
"@redux-tools/reducers-react": "^0.5.0",
)
After correcting it I am getting following error now:

Uncaught Invariant Violation: The injector config is undefined.
    at invariant (webpack-internal:///../node_modules/invariant/browser.js:38:15)
    at makeHook (webpack-internal:///../node_modules/@redux-tools/reducers-react/node_modules/@redux-tools/injectors-react/es/redux-tools-injectors-react.js:121:51)
    at eval (webpack-internal:///../node_modules/@redux-tools/reducers-react/es/redux-tools-reducers-react.js:93:96)
    at Module.../node_modules/@redux-tools/reducers-react/es/redux-tools-reducers-react.js (http://localhost:3300/static/js/vendor.chunk.js:19163:1)
    at __webpack_require__ (http://localhost:3300/static/js/runtime.bundle.js:791:30)
    at fn (http://localhost:3300/static/js/runtime.bundle.js:151:20)
    at Module.eval (webpack-internal:///../packages/app-vf-adam-orders/src/components/Root/Root.js:13:85)
    at eval (webpack-internal:///../packages/app-vf-adam-orders/src/components/Root/Root.js:78:30)
    at Module.../packages/app-vf-adam-orders/src/components/Root/Root.js (http://localhost:3300/static/js/main.chunk.js:33:1)
    at __webpack_require__ (http://localhost:3300/static/js/runtime.bundle.js:791:30)

**Comment by wafflepie** [comment]
Please try upgrading to the newest version of Redux Tools (all packages to 0.8.2)

**Comment by shahzad185** [comment]
Hi

Thank you for your support.

I can confirm that issue is resolved after updating to suggested versions.

**Comment by shahzad185** [comment]
Thank you very much for your support as issue is resolved after upgrading to recommended version.

**Comment by wafflepie** [comment]
Awesome! Happy to help. Let me know if you have any other issues :)
